# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 9,21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Uptime Action
        # You may pin to the exact commit or the version.
        # uses: srt32/uptime@958231f4d95c117f08eb0fc70907e80d0dfedf2b
        uses: srt32/uptime@v0.2.1
        with:
          # which url to hit
          url-to-hit: http://dublinbikes.ml/
          # which http response statuses are expected
          expected-statuses: 200
